// Generated by CoffeeScript 1.7.1
(function() {
  var app, dotenv, express, request, soap, wsdl, xml2js, _;

  dotenv = require('dotenv');

  dotenv.load();

  express = require('express');

  app = express();

  app.use(express.compress());

  soap = require('soap');

  _ = require('underscore');

  request = require('request');

  xml2js = require('xml2json');

  wsdl = './lib/russianpost/wsdl/russianpost_1.wsdl';

  soap.createClient(wsdl, function(err, client) {
    var fetchRussianPost, fetchUSPS, port;
    if (err) {
      return console.error(err);
    } else {
      fetchRussianPost = function(req, res) {
        var message;
        message = {
          Barcode: req.params.barcode,
          MessageType: 0
        };
        return client.GetOperationHistory(message, function(err, result) {
          if (err) {
            console.error(err);
            return res.json(500, {
              error: err
            });
          } else if (result) {
            return res.json(result);
          } else {
            return res.send(404);
          }
        }, {
          timeout: 4000
        });
      };
      fetchUSPS = function(req, res) {
        var query, url;
        query = "<TrackFieldRequest USERID=\"" + process.env.USPS_USER_ID + "\"> <TrackID ID=\"" + req.params.barcode + "\"></TrackID> </TrackFieldRequest>";
        url = "http://production.shippingapis.com/ShippingAPI.dll?API=TrackV2&XML=" + query;
        return request(url, function(err, response, body) {
          if (err) {
            console.log(err);
            return res.send(500);
          } else {
            return res.json(xml2js.toJson(body, {
              object: true
            }));
          }
        });
      };
      app.get('/russianpost/:barcode', fetchRussianPost);
      app.get('/usps/:barcode', fetchUSPS);
      port = process.env.PORT || 3000;
      app.listen(port);
      return console.log("[INFO] Listening on port " + port);
    }
  });

}).call(this);
